version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: absensi-api-container
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:mysecretpassword@postgres:5432/absensi_app?sslmode=disable"
    networks:
      - app-network # Gunakan network yang sama seperti Postgres

networks:
  app-network:
    external: true # Pastikan menggunakan network yang sama dengan Postgres
