version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: absensi_app
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network # Hubungkan PostgreSQL ke network yang sama

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: absensi-api-container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:mysecretpassword@postgres:5432/absensi_app?sslmode=disable"
    networks:
      - app-network # Hubungkan API ke network yang sama

networks:
  app-network: # Pastikan network didefinisikan dengan benar
    driver: bridge

volumes:
  db-data:
